apiVersion: v1
kind: Pod
metadata:
  name: existing-pod-0
  labels:
    podGroup: "A"
    minAvailable: "3"
spec:
  schedulerName: my-scheduler
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: existing-pod-1
  labels:
    podGroup: "A"
    minAvailable: "3"
spec:
  restartPolicy: Never
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: existing-pod-2
  labels:
    podGroup: "A"
    minAvailable: "3"
spec:
  restartPolicy: Never
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"
---

apiVersion: v1
kind: Pod
metadata:
  name: existing-pod-3
  labels:
    podGroup: "B"
    minAvailable: "3"
spec:
  restartPolicy: Never
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: existing-pod-4
  labels:
    podGroup: "B"
    minAvailable: "2"
spec:
  restartPolicy: Never
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"